export const portfolioContent = {
  hero: {
    name: "Utkarsh Pandey",
    brand: "JustXutkarsh",
    title: "AI Engineer building production intelligent systems.",
    subtitle:
      "I build applied AI systems that combine LLMs, machine learning, retrieval, agents, and scalable backend engineering.",
    location: "Pune, India",
  },
  about: [
    "I build AI systems across research, architecture, model or LLM integration, backend APIs, deployment, and real user feedback.",
    "My core keywords are LLMs, multi-agent systems, RAG, vector databases, OpenAI API, GPT-4o, CLIP, Tavily API, ChromaDB, FAISS, Supabase, Streamlit, Vercel, Render, AI automation, and production inference workflows.",
    "Full stack engineering is the delivery layer: I use React, Node.js, APIs, UI/UX, and cloud deployment to turn AI pipelines into usable products.",
  ],
  experience: [
    {
      company: "Autonix",
      role: "Co-Founder & AI Systems Lead",
      period: "AI Automation Agency",
      points: [
        "Co-founded an AI automation agency building end-to-end AI systems for local service businesses across dental, aesthetic, and home service verticals in UK and UAE markets",
        "Deployed a production AI receptionist for a UK dental clinic using Vapi, n8n, and Google Calendar",
        "Built autonomous inbound call booking workflows with production-ready automation handoffs",
      ],
    },
    {
      company: "Own The Story",
      role: "Engineering Contributor",
      period: "Production Systems",
      points: ["Supported production web systems", "Built reliable product features and APIs", "Applied full stack engineering where it improved delivery"],
    },
  ],
  projects: [
    {
      title: "ASTRAM",
      slug: { current: "astram" },
      homepage: true,
      featured: true,
      created: "2026-05-20T00:00:00.000Z",
      imageUrl: "/images/projects/astram.svg",
      mainImage: { alt: "ASTRAM AI deployment planner" },
      categories: [{ title: "LLM Planning" }, { title: "Risk Analysis" }],
      subcategories: [{ title: "Historical Retrieval" }, { title: "Similarity Search" }, { title: "PDF Reports" }],
      summary: "AI traffic intelligence app that forecasts event-driven congestion, recommends manpower and barricading, and generates diversion plans.",
      body: [{ _type: "block", style: "normal", children: [{ text: "ASTRAM is an AI-powered traffic management platform with congestion risk scoring, temporal analysis, GPT-based event planning, similar incident retrieval, PDF reports, and diversion playbooks.", marks: [] }] }],
      links: [{ label: "GitHub", url: "https://github.com/JustXutkarsh/Astram-traffic-intelligence-app" }],
    },
    {
      title: "Agentic Research PRO",
      slug: { current: "agentic-research-pro" },
      homepage: true,
      featured: true,
      created: "2026-05-10T00:00:00.000Z",
      imageUrl: "/images/projects/agentic-research-pro.svg",
      mainImage: { alt: "Agentic Research PRO autonomous research graph" },
      categories: [{ title: "AI Agents" }, { title: "Research" }],
      subcategories: [{ title: "Multi-Agent Architecture" }, { title: "Tavily" }, { title: "FAISS" }, { title: "OpenAI" }, { title: "Report Generation" }],
      summary: "Autonomous multi-agent research system for web search, scraping, chunking, embeddings, retrieval, reasoning, and PDF export.",
      body: [{ _type: "block", style: "normal", children: [{ text: "Agentic Research PRO is a modular agent pipeline with Tavily search, article scraping, semantic chunking, OpenAI embeddings, vector retrieval, structured report writing, and PDF export with source links.", marks: [] }] }],
      links: [{ label: "GitHub", url: "https://github.com/JustXutkarsh/Agentic-Resarch-Pro" }],
    },
    {
      title: "MedMind AI",
      slug: { current: "medmind-ai" },
      homepage: true,
      featured: false,
      created: "2026-04-24T00:00:00.000Z",
      imageUrl: "/images/projects/medmind-ai.svg",
      mainImage: { alt: "MedMind AI healthcare analysis" },
      categories: [{ title: "Healthcare AI" }, { title: "Retrieval" }],
      subcategories: [{ title: "GPT" }, { title: "Medical Analysis" }, { title: "Knowledge Retrieval" }, { title: "Supabase" }],
      summary: "Healthcare AI assistant for GPT-powered analysis with medical knowledge retrieval and Supabase-backed application data.",
      body: [{ _type: "block", style: "normal", children: [{ text: "MedMind AI applies GPT and retrieval to healthcare analysis workflows with a practical product interface.", marks: [] }] }],
      links: [],
    },
    {
      title: "SkyVision",
      slug: { current: "skyvision" },
      homepage: true,
      featured: false,
      created: "2026-04-08T00:00:00.000Z",
      imageUrl: "/images/projects/skyvision.svg",
      mainImage: { alt: "SkyVision multimodal travel search" },
      categories: [{ title: "Multimodal AI" }, { title: "Vector Search" }],
      subcategories: [{ title: "CLIP" }, { title: "Computer Vision" }, { title: "Travel Search" }],
      summary: "Multimodal airport and airline logo search using natural language, image upload, CLIP embeddings, and MariaDB vector search.",
      body: [{ _type: "block", style: "normal", children: [{ text: "SkyVision lets users search visually similar airports and airline logos with text, image, or hybrid queries using CLIP embeddings, FastAPI, Streamlit, and MariaDB vector indexing.", marks: [] }] }],
      links: [{ label: "GitHub", url: "https://github.com/JustXutkarsh/SkyVision" }],
    },
    {
      title: "Traffic Demand Prediction",
      slug: { current: "traffic-demand-prediction" },
      homepage: true,
      featured: false,
      created: "2026-03-22T00:00:00.000Z",
      imageUrl: "/images/projects/traffic-demand-prediction.svg",
      mainImage: { alt: "Traffic demand prediction pipeline" },
      categories: [{ title: "Machine Learning" }, { title: "Forecasting" }],
      subcategories: [{ title: "Feature Engineering" }, { title: "XGBoost" }, { title: "Prediction Pipeline" }],
      summary: "Flipkart GRID forecasting pipeline with feature engineering, XGBoost-style modeling, and demand prediction workflows.",
      body: [{ _type: "block", style: "normal", children: [{ text: "Traffic Demand Prediction focuses on structured forecasting, feature engineering, model evaluation, and prediction pipeline tuning for the Flipkart GRID challenge.", marks: [] }] }],
      links: [{ label: "GitHub", url: "https://github.com/JustXutkarsh/flipkartGrid" }],
    },
  ],
  skills: {
    "Artificial Intelligence": ["Large Language Models", "RAG", "Prompt Engineering", "AI Agents", "Embeddings", "Vector Databases", "Model Evaluation", "Generative AI"],
    "Machine Learning": ["Deep Learning", "PyTorch", "TensorFlow", "Scikit-learn", "XGBoost", "Pandas", "NumPy"],
    Backend: ["Python", "FastAPI", "Node", "REST APIs", "Authentication"],
    Databases: ["PostgreSQL", "Supabase", "ChromaDB", "Redis"],
    Infrastructure: ["Docker", "Git", "AWS", "Vercel", "Render"],
    Frontend: ["React", "SvelteKit", "TypeScript", "JavaScript"],
  },
  achievements: [
    { logo: "Lovable", logoPath: "/logos/lovable.png", title: "Lovable VibeHack 2025: #2", detail: "International virtual hackathon under Hack With India; secured 2nd place in September 2025.", metrics: [{ label: "Teams beaten for 2nd place", value: 600, suffix: "+", precision: 0 }], milestoneDate: "Sep 2025", milestoneTitle: "VIBE Hacks 2025", milestoneDetail: "2nd place among 600+ teams" },
    { logo: "Flipkart", logoPath: "/logos/flipkart.svg", title: "Flipkart GRID semi-finalist", detail: "Qualified from 35K+ teams in May 2026 with 91.96% accuracy.", metrics: [{ label: "Flipkart GRID participants", value: 35000, suffix: "+", precision: 0 }, { label: "Best model accuracy", value: 91.96, suffix: "%", precision: 2 }], milestoneDate: "May 2026", milestoneTitle: "Flipkart GRID / HackerEarth traffic prediction", milestoneDetail: "Semifinalist among 35,000+ participants; best score 91.96% accuracy" },
    { logo: "MariaDB", logoPath: "/logos/mariadb.png", title: "SkyVision: MariaDB Hackathon finalist", detail: "International MariaDB hackathon finalist: top 70 among 30K+ participants in November 2025.", metrics: [{ label: "SkyVision CLIP relevance", value: 85, suffix: "%", precision: 0 }], milestoneDate: "Nov 2025", milestoneTitle: "SkyVision: MariaDB Hackathon", milestoneDetail: "Top 70 finalist among 30,000+ participants" },
    { icon: "🏆", title: "#6 intercollege hackathon", detail: "Ranked #6 across Pune colleges in October 2025 in a hackathon organized by Dr. D. Y. Patil Institute of Technology.", milestoneDate: "Oct 2025", milestoneTitle: "InterCollege Hackathon", milestoneDetail: "6th among 200+ teams" },
    { icon: "ML", title: "HackerEarth traffic prediction challenge", detail: "Same traffic forecasting challenge as Flipkart GRID; best score was 91.96% accuracy in May 2026.", metrics: [{ label: "CatBoost traffic ROC-AUC", value: 0.819, precision: 3 }] },
    { logo: "Smart India Hackathon", logoPath: "/logos/smart-india-hackathon.png", title: "Smart India Hackathon 2025", detail: "Qualified till Stage 2." },
  ],
  certifications: [
    { title: "Supervised Machine Learning: Regression and Classification", issuer: "DeepLearning.AI, Stanford University, Coursera", href: "/certificates/coursera-supervised-ml.pdf" },
    { title: "Using OpenAI APIs: Exploring APIs with the OpenAI Playground", issuer: "Skillsoft", href: "/certificates/skillsoft-openai-playground.png", image: "/certificates/skillsoft-openai-playground.png" },
    { title: "VibeHack 2025 Certificate of Excellence", issuer: "Hack With India x Lovable", href: "/certificates/vibe-hack-2025.png", image: "/certificates/vibe-hack-2025.png" },
    { title: "Hackathon Winner Certificate", issuer: "Certificate shared by Utkarsh Pandey", href: "/certificates/hackathon-winner.pdf" },
  ],
  socials: [
    { label: "GitHub", url: "https://github.com/JustXutkarsh" },
    { label: "LinkedIn", url: "https://www.linkedin.com/in/utkarsh-pandey2005/" },
    { label: "Email", url: "mailto:utkarshp034@gmail.com" },
    { label: "Resume", url: "/resume.pdf" },
  ],
};
